version: '0.1'
services:
  taskmaster-pro:
    build:
      context:
        dockerfile:Dockerfile
      args:
        - API_URL=https://fakeapi.taskmaster.com
        - NODE_ENV:production
      ports:
        - "3000:5173"
      environment:
        - API_URL=https://fakeapi.taskmaster.com
        - DATABASE_URL=postgres://user:password@localhost:5432/taskmaster
        - NODE_ENV=production
        - REACT_APP_VERSION=1.0.0
      volumes:
        - nginx-cache:/var/cache/nginx
      env_file:
        - .env
      restart: unless-stopped
      network: 
        - taskmaster-network
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.taskmaster.rule=Host(`taskmaster.local`)"
        - "traefik.http.services.taskmaster.loadbalancer.server.port=3000"

      networks:
        taskmaster-network:
          driver: bridge